phrase:
  access_token: 5beb96b40c9ba8156509666ac9296a73c04931e0bc20762855bfe3b05e8b8841
  project_id: 3b344bb0c4178955d38105deca4ccbea
  file_format: strings 
  push:
    sources:
      - file: en.strings
        params:
          locale_id: bb44d618d2cf371133837fbc05250719
          update_translations: true
          autotranslate: true
  pull:
    targets:
      - file: ja.strings
        params:
          locale_id: 1de65fadaee5697dcbe09c75def7bc6d
      - file: fr.strings
        params:
          locale_id: f2350c7949f48a29ea94cb98ca509aa8
