phrase:
  access_token: a24a987ac9fc81dd42bd4915b03d67e034da696565a15d044cd0c8b73ed46b69
  project_id: 3b344bb0c4178955d38105deca4ccbea
  file_format: strings 
  push:
    sources:
      - file: en.strings
        params:
          locale_id: b61cb8708e16acc3098aa1baaed702dc
          update_translations: true
          autotranslate: true
  pull:
    targets:
      - file: ja.strings
        params:
          locale_id: 081114eacb0a89b8ef526b35eb13b95c
      - file: fr.strings
        params:
          locale_id: f2350c7949f48a29ea94cb98ca509aa8
