phrase:
  access_token: 00e2859fcbef2731816baab668d188b9d94dd2d59aac400f26059768fdf93556
  project_id: 3b344bb0c4178955d38105deca4ccbea
  file_format: strings 
  push:
    sources:
      - file: en.strings
        params:
          locale_id: en
          update_translations: true
          autotranslate: true
  pull:
    targets:
      - file: ja.strings
        params:
          locale_id: ja
      - file: fr.strings
        params:
          locale_id: fr
