phrase:
  access_token: 5beb96b40c9ba8156509666ac9296a73c04931e0bc20762855bfe3b05e8b8841
  project_id: 3b344bb0c4178955d38105deca4ccbea
  file_format: strings 
  push:
    sources:
      - file: en.strings
        params:
          locale_id: e0b63971e25b1ec83333f5aea57cf5fb
          update_translations: true
          autotranslate: true
      - file: en.strings
        params:
          locale_id: b61cb8708e16acc3098aa1baaed702dc
          update_translations: true
          autotranslate: true
  pull:
    targets:
      - file: ja.strings
        params:
          locale_id: 081114eacb0a89b8ef526b35eb13b95c
      - file: fr.strings
        params:
          locale_id: f2350c7949f48a29ea94cb98ca509aa8
